### ISSUE TITLE
Would be nice to be able to customise the clear button class name 

### ISSUE THREAD

**Issue by james-siteclick** [KeitIG/react-simple-input#2]
e.g. in options:
```
Input.defaultProps = {
...
        classNameClearButton          : '',
...
};
```

Line 34
```
clearButton = <div className={ 'react-simple-input-clear ' + this.props.classNameClearButton } onClick={ () => { this.clear() } }>&times;</div>
```

**Comment by martpie** [comment]
Why not add multiple classes to the container, it would do the same thing right ? Or do you have a really specific usecase ?

**Comment by james-siteclick** [comment]
Thank you very much for your reply.  

We are trying to follow a BEM naming convention for our classes, so we would like to have something like:
```
<div class="react-simple-input">
  <div class="react-simple-input__clear"></div>
</div>
```

**Comment by martpie** [comment]
Ok I see.

I made some research about that, and I will close this without fixing it. Some references:

Harry Roberts on Modularity:
https://twitter.com/csswizardry/status/539726989159301121

BEM docs about redefinition level and third party libs:
https://en.bem.info/methodology/key-concepts/#redefinition-level

Hope it won't bother you too much :)

**Comment by james-siteclick** [comment]
OK thanks for looking at it
